package vista;

import controlador.EmpleadosController;
import controlador.ctrlUsuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class frmLogin extends javax.swing.JFrame {
    
    EmpleadosController controller;
    boolean contraseñaVisible;
    
    public frmLogin() {
        initComponents();
        txtAlertaEmail.setVisible(false);
        txtAlertaPassword.setVisible(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Login - DriveLux");
        this.setSize(new Dimension(720, 500));
        controller = new EmpleadosController();
        contraseñaVisible = false;
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/iconCar.png"));
        return retValue;
    }
    
    private void Login(){
        if(txtEmail.getText().isEmpty())
            txtAlertaEmail.setVisible(true);
        if(psPassword.getText().isEmpty())
            txtAlertaPassword.setVisible(true);
        if(!txtEmail.getText().isEmpty() && !psPassword.getText().isEmpty()){
            
            ctrlUsuario controlUsuario = new ctrlUsuario();
            String email = txtEmail.getText();
            String password = psPassword.getText();
            
            if(controlUsuario.loginUser(email, password)){
                String rol = controller.getRolByEmail(email);
                int idEmployee = controller.getIdByEmail(email);
                if(rol.equals("Supervisor")){
                    SistemaAdmin menuPrincipal = new SistemaAdmin(idEmployee);
                    menuPrincipal.setVisible(true);
                    this.setVisible(false);
                } else {
                    SistemaVendedor menuSecundario = new SistemaVendedor(idEmployee);
                    menuSecundario.setVisible(true);
                    this.setVisible(false);
                }
            }
            else 
                JOptionPane.showMessageDialog(null, "Credenciales incorrectas");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogin = new javax.swing.JLabel();
        panelComponentes = new javax.swing.JPanel();
        txtBienvenido = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        psPassword = new javax.swing.JPasswordField();
        imgPaswword = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        txtAlertaEmail = new javax.swing.JLabel();
        txtAlertaPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car's_login.jpg"))); // NOI18N
        getContentPane().add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        panelComponentes.setBackground(new java.awt.Color(255, 255, 255));
        panelComponentes.setForeground(new java.awt.Color(255, 255, 255));
        panelComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBienvenido.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtBienvenido.setText("¡Bienvenido!");
        panelComponentes.add(txtBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 67, -1, -1));

        txtEmpresa.setText("@ Concesionario DriveLux");
        panelComponentes.add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 120, 170, -1));

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        panelComponentes.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 187, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        panelComponentes.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 187, 224, -1));

        psPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psPasswordActionPerformed(evt);
            }
        });
        psPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psPasswordKeyPressed(evt);
            }
        });
        panelComponentes.add(psPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 249, 224, -1));

        imgPaswword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        panelComponentes.add(imgPaswword, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 247, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelComponentes.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 323, 180, 35));

        txtAlertaEmail.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txtAlertaEmail.setForeground(new java.awt.Color(204, 0, 0));
        txtAlertaEmail.setText("¡Introduce tu correo!");
        panelComponentes.add(txtAlertaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 215, -1, -1));

        txtAlertaPassword.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txtAlertaPassword.setForeground(new java.awt.Color(204, 0, 0));
        txtAlertaPassword.setText("¡Introduce una contraseña!");
        panelComponentes.add(txtAlertaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 277, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelComponentes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 30, 20));

        getContentPane().add(panelComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 340, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void psPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psPasswordActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        this.Login();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode () == evt.VK_ENTER)
            psPassword.requestFocus();
    }//GEN-LAST:event_txtEmailKeyPressed

    private void psPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
            this.Login();
    }//GEN-LAST:event_psPasswordKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (contraseñaVisible) { 
                    psPassword.setEchoChar('*');
                } else {
                    psPassword.setEchoChar((char) 0);
                }
                contraseñaVisible = !contraseñaVisible;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel imgPaswword;
    private javax.swing.JLabel imgUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPasswordField psPassword;
    private javax.swing.JLabel txtAlertaEmail;
    private javax.swing.JLabel txtAlertaPassword;
    private javax.swing.JLabel txtBienvenido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtEmpresa;
    // End of variables declaration//GEN-END:variables
}
